meta_product_name:  "Running Separeted but to together"
meta_title: "Connecting Virtual Runners"
meta_description: "Using technology to run together but at a distance"
meta_image: "resized_seo_image.png" # should exist in `app/assets/images/`
twitter_account: "@VirtualRunners1"   # required for Twitter Cards
